ALTER TABLE checkins ADD COLUMN photo_size_bytes INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS r2_monthly_usage (
  month TEXT PRIMARY KEY,
  class_a_ops INTEGER NOT NULL DEFAULT 0,
  class_b_ops INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
